=== rogeriesmontsia/XML_M4/Cotxes.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT concessionari (Nom,foto,marques)>
<!ATTLIST concessionari
  xmlns CDATA #FIXED ''
  NomConcessionari CDATA #REQUIRED>

<!ELEMENT Nom (#PCDATA)>
<!ATTLIST Nom
  xmlns CDATA #FIXED ''>

<!ELEMENT marques (Audi,Seat,Volkswagen)>
<!ATTLIST marques
  xmlns CDATA #FIXED ''>

<!ELEMENT Audi (modelsAudi)>
<!ATTLIST Audi
  xmlns CDATA #FIXED ''
  Fabricacio NMTOKEN #REQUIRED>

<!ELEMENT Seat (modelsSeat)>
<!ATTLIST Seat
  xmlns CDATA #FIXED ''
  Fabricacio NMTOKEN #REQUIRED>

<!ELEMENT Volkswagen (modelsVW)>
<!ATTLIST Volkswagen
  xmlns CDATA #FIXED ''
  Fabricacio NMTOKEN #REQUIRED>

<!ELEMENT modelsAudi (Audi_A1_Sportback,Audi_S8_TFSI,Audi_A4)>
<!ATTLIST modelsAudi
  xmlns CDATA #FIXED ''>

<!ELEMENT modelsSeat (Seat_Leon,Seat_Ibiza,Seat_Ateca)>
<!ATTLIST modelsSeat
  xmlns CDATA #FIXED ''>

<!ELEMENT modelsVW (Volkswagen_ArteonR,Volkswagen_Tiguan,
                    Volkswagen_Polo)>
<!ATTLIST modelsVW
  xmlns CDATA #FIXED ''>

<!ELEMENT Audi_A1_Sportback (model,foto,venedor,any,descripcio,motor,
                             gama)>
<!ATTLIST Audi_A1_Sportback
  xmlns CDATA #FIXED ''>

<!ELEMENT Audi_S8_TFSI (model,foto,venedor,any,descripcio,motor,gama)>
<!ATTLIST Audi_S8_TFSI
  xmlns CDATA #FIXED ''>

<!ELEMENT Audi_A4 (model,foto,venedor,any,descripcio,motor,gama)>
<!ATTLIST Audi_A4
  xmlns CDATA #FIXED ''>

<!ELEMENT Seat_Leon (model,foto,venedor,any,descripcio,motor,gama)>
<!ATTLIST Seat_Leon
  xmlns CDATA #FIXED ''>

<!ELEMENT Seat_Ibiza (model,foto,venedor,any,descripcio,motor,gama)>
<!ATTLIST Seat_Ibiza
  xmlns CDATA #FIXED ''>

<!ELEMENT Seat_Ateca (model,foto,venedor,any,descripcio,motor,gama)>
<!ATTLIST Seat_Ateca
  xmlns CDATA #FIXED ''>

<!ELEMENT Volkswagen_ArteonR (model,foto,venedor,fabricant,any,
                              descripcio,motor,gama)>
<!ATTLIST Volkswagen_ArteonR
  xmlns CDATA #FIXED ''>

<!ELEMENT Volkswagen_Tiguan (model,foto,venedor,fabricant,any,
                             descripcio,motor,gama)>
<!ATTLIST Volkswagen_Tiguan
  xmlns CDATA #FIXED ''>

<!ELEMENT Volkswagen_Polo (model,foto,venedor,fabricant,any,descripcio,
                           motor,gama)>
<!ATTLIST Volkswagen_Polo
  xmlns CDATA #FIXED ''>

<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto
  xmlns CDATA #FIXED ''>

<!ELEMENT model (#PCDATA)>
<!ATTLIST model
  xmlns CDATA #FIXED ''>

<!ELEMENT venedor (#PCDATA)>
<!ATTLIST venedor
  xmlns CDATA #FIXED ''>

<!ELEMENT any (#PCDATA)>
<!ATTLIST any
  xmlns CDATA #FIXED ''>

<!ELEMENT descripcio (#PCDATA)>
<!ATTLIST descripcio
  xmlns CDATA #FIXED ''>

<!ELEMENT motor (#PCDATA)>
<!ATTLIST motor
  xmlns CDATA #FIXED ''>

<!ELEMENT gama (gamaBaixa,gamaMitja,gamaAlta)>
<!ATTLIST gama
  xmlns CDATA #FIXED ''>

<!ELEMENT gamaBaixa (#PCDATA)>
<!ATTLIST gamaBaixa
  xmlns CDATA #FIXED ''>

<!ELEMENT gamaMitja (#PCDATA)>
<!ATTLIST gamaMitja
  xmlns CDATA #FIXED ''>

<!ELEMENT gamaAlta (#PCDATA)>
<!ATTLIST gamaAlta
  xmlns CDATA #FIXED ''>

<!ELEMENT fabricant (#PCDATA)>
<!ATTLIST fabricant
  xmlns CDATA #FIXED ''>

=== rogeriesmontsia/XML_M4/Cotxes_Valida_DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Audi_A1.xsl" ?>
<!DOCTYPE concessionari SYSTEM "Cotxes.dtd">
<concessionari NomConcessionari="Concessionari Andorra">
    <Nom>Andorra</Nom>
    <foto>http://es.centreprestigiautomobils.ad/Content/img/slider/482438566.jpg</foto>
    <marques>
        <Audi Fabricacio="Alemana">
            <modelsAudi>
                <Audi_A1_Sportback>
                    <model>Audi A1 Sportback</model>
                    <foto>http://www.listadecarros.com/wp-content/uploads/2014/05/Audi-A1-Sportback-2014-7.jpg</foto>
                    <venedor>Richard</venedor>
                    <any>2023</any>
                    <descripcio>Sent el dinamisme i l'esportivitat de l'Audi A1 Sportback.
                        Un urbanita 100% connectat, amb tota la tecnologia, disseny i diversió que cerques.</descripcio>
                    <motor>207 CV</motor>
                    <gama>
                        <gamaBaixa>29.501,00 €</gamaBaixa>
                        <gamaMitja>34.209,00 €</gamaMitja>
                        <gamaAlta>47.605,00 €</gamaAlta>
                    </gama>
                </Audi_A1_Sportback>
                <Audi_S8_TFSI>
                    <model>Audi S8</model>
                    <foto>https://cdn.motor1.com/images/mgl/28MWB/s3/2022-audi-s8.jpg</foto>
                    <venedor>Richard</venedor>
                    <any>2023</any>
                    <descripcio>Amb un disseny imponent i unes prestacions esportives de competició,
                        l'Audi RS 7 Sportback performance combina sensacions, confort i classe en un Gran
                        Turisme únic.</descripcio>
                    <motor>630 CV</motor>
                    <gama>
                        <gamaBaixa>192.101,00 €</gamaBaixa>
                        <gamaMitja>214.321,00 €</gamaMitja>
                        <gamaAlta>227.840,00 €</gamaAlta>
                    </gama>
                </Audi_S8_TFSI>
                <Audi_A4>
                    <model>Audi A4</model>
                    <foto>https://1.bp.blogspot.com/-efRFbk6TXUA/YCsFLJBSVkI/AAAAAAAAqnw/tXOLzqXo0NQEl_7hou-tKhi-I0m1IJAdgCLcBGAsYHQ/s2048/Novo-Audi-A4-2022-Brasil%2B%252846%2529.jpg</foto>
                    <venedor>Richard</venedor>
                    <any>2023</any>
                    <descripcio>Benvingut a un SUV de luxe ampli i versàtil.
                        Amb espai per a set persones, un disseny poderós i les tecnologies dajuda a
                        la conducció més avançades.</descripcio>
                    <motor>507 CV</motor>
                    <gama>
                        <gamaBaixa>84.525,00 €</gamaBaixa>
                        <gamaMitja>101.235,00 €</gamaMitja>
                        <gamaAlta>156.925,00 €</gamaAlta>
                    </gama>
                </Audi_A4>
            </modelsAudi>
        </Audi>
        <Seat Fabricacio="Espanyola">
            <modelsSeat>
                <Seat_Leon>
                    <model>Seat Leon</model>
                    <foto>https://www.gtopcars.com/wp-content/uploads/2021/07/2022-SEAT-Leon-Cupra-e-Hybrid.jpg</foto>
                    <venedor>Roger</venedor>
                    <any>2022</any>
                    <descripcio>El SEAT León és més atrevit, més ampli i té una llum posterior infinita LED. Hem gaudit
                        fent-ho i es nota. Descobreix el seu disseny Color exterior Reflecteix el que portes dins.
                        Metal·litzat Suau Gris Graphene SEAT CONNECT Tot es pot aconseguir.</descripcio>
                    <motor>165 CV</motor>
                    <gama>
                        <gamaBaixa>26.000 €</gamaBaixa>
                        <gamaMitja>32.500 €</gamaMitja>
                        <gamaAlta>46.500 €</gamaAlta>
                    </gama>
                </Seat_Leon>
                <Seat_Ibiza>
                    <model>Seat Ibiza</model>
                    <foto>https://i.blogs.es/b55597/seat-ibiza-2022_/1366_2000.jpeg</foto>
                    <venedor>Roger</venedor>
                    <any>2022</any>
                    <descripcio>El nou SEAT Ibiza no és un cotxe per anar a mitges. Amb línies més dinàmiques, noves
                        llantes d'aliatge de 46 cm (18'') i fars Full LED, l'últim que passaràs és desapercebut. Anar a
                        Disseny N'hi ha més. El teu Nou SEAT Ibiza i tu teniu més coses en comú.</descripcio>
                    <motor>116 CV</motor>
                    <gama>
                        <gamaBaixa>12.000 €</gamaBaixa>
                        <gamaMitja>18.000 €</gamaMitja>
                        <gamaAlta>25.000 €</gamaAlta>
                    </gama>
                </Seat_Ibiza>
                <Seat_Ateca>
                    <model>Seat Ateca</model>
                    <foto>https://www.lifequestalliance.com/wp-content/uploads/2021/05/2022-Seat-Ateca-suzuki-1.5-tsi-akrapovic-4drive-2-exterior.jpg</foto>
                    <venedor>Roger</venedor>
                    <any>2022</any>
                    <descripcio>El Nou SEAT Ateca s'adapta a la teva necessitat de viure més experiències i recórrer
                        territoris inexplorats. Anar a disseny N'hi ha més. Coneix més detalls tècnics sobre el teu SEAT
                        Ateca en els següents vídeos, per viure més al gran amb ell. Veure vídeos Disseny Molt més que
                        uns retocs. Nova graella davantera.</descripcio>
                    <motor>90 CV</motor>
                    <gama>
                        <gamaBaixa>20.000 €</gamaBaixa>
                        <gamaMitja>26.500 €</gamaMitja>
                        <gamaAlta>34.900 €</gamaAlta>
                    </gama>
                </Seat_Ateca>
            </modelsSeat>
        </Seat>
        <Volkswagen Fabricacio="Alemana">
            <modelsVW>
                <Volkswagen_ArteonR>
                    <model>Volkswagen Arteon R</model>
                    <foto>https://i.ytimg.com/vi/RgVYhgtXNgw/maxresdefault.jpg</foto>
                    <venedor>Joan</venedor>
                    <fabricant>Volskwagen</fabricant>
                    <any>2018</any>
                    <descripcio>El disseny perfecte, la comoditat que vols al volant i
                        un extra de rendiment s'han unit al Nuevo Arteon R perquè
                        gaudeixis del millor company de viatges. Poques vegades
                        la potència havia tingut una forma tan bona.
                        Què esperes per viure-la?</descripcio>
                    <motor>Arteon R 2.0 TSI 235 kW (320 CV)</motor>
                    <gama>
                        <gamaBaixa>52680 €</gamaBaixa>
                        <gamaMitja>60320 €</gamaMitja>
                        <gamaAlta>72600 €</gamaAlta>
                    </gama>
                </Volkswagen_ArteonR>
                <Volkswagen_Tiguan>
                    <model>Volkswagen Tiguan</model>
                    <foto>https://cdn.motor1.com/images/mgl/PpZ0X/s1/2022-volkswagen-tiguan-eu.jpg</foto>
                    <venedor>Joan</venedor>
                    <fabricant>Volskwagen</fabricant>
                    <any>2016</any>
                    <descripcio>Emoció en estat pur.
                        El Tiguan ha arribat per ampliar el teu ventall de possibilitats.
                        Si cada viatge era l'oportunitat de viure una aventura nova, ara ho faràs més connectat,
                        amb més potència i tot el caràcter d'aquest SUV. Una versió que se supera per estar al dia,
                        com tu.</descripcio>
                    <motor>Tiguan 2.0 TSI R 4Motion DSG 235kW (320CV)</motor>
                    <gama>
                        <gamaBaixa>34990 €</gamaBaixa>
                        <gamaMitja>44085 €</gamaMitja>
                        <gamaAlta>67301 €</gamaAlta>
                    </gama>
                </Volkswagen_Tiguan>
                <Volkswagen_Polo>
                    <model>Volkswagen Polo</model>
                    <foto>https://i.ytimg.com/vi/rXT1VzQvMog/maxresdefault.jpg</foto>
                    <venedor>Joan</venedor>
                    <fabricant>Volskwagen</fabricant>
                    <any>2017</any>
                    <descripcio>Qui digui que un cotxe petit no et pot fer sentir coses grans, s'equivoca.
                        El Nuevo Polo té un disseny modern i l'últim en tecnologia perquè gaudeixis del company
                        que vols al teu dia a dia. Us fareu inseparables.</descripcio>
                    <motor>Polo 2.0 TSI GTI DSG 81kW (207CV)</motor>
                    <gama>
                        <gamaBaixa>18844 €</gamaBaixa>
                        <gamaMitja>22654 €</gamaMitja>
                        <gamaAlta>30003 €</gamaAlta>
                    </gama>
                </Volkswagen_Polo>
            </modelsVW>
        </Volkswagen>
    </marques>
</concessionari>
